export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  REPORT_NOT_FOUND: "REPORT_NOT_FOUND",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  REQUEST_NOT_FOUND: "REQUEST_NOT_FOUND",
  INVALID_REVIEW_ACTION: "INVALID_REVIEW_ACTION",
  ROUTE_HAS_OPEN_BARRIER: "ROUTE_HAS_OPEN_BARRIER",
  REQUEST_NOT_ACCEPTABLE: "REQUEST_NOT_ACCEPTABLE"
} as const;
