export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  BARRIER_REPORT_NOT_FOUND: "BARRIER_REPORT_NOT_FOUND",
  ROUTE_PLAN_NOT_FOUND: "ROUTE_PLAN_NOT_FOUND",
  ASSISTANCE_REQUEST_NOT_FOUND: "ASSISTANCE_REQUEST_NOT_FOUND",
  INVALID_REVIEW_ACTION: "INVALID_REVIEW_ACTION",
  ROUTE_BLOCKED_BY_BARRIER: "ROUTE_BLOCKED_BY_BARRIER",
  ASSISTANCE_STATE_CONFLICT: "ASSISTANCE_STATE_CONFLICT"
} as const;
