export const FLOW_EVENT_TYPES = {
  BARRIER_REVIEWED: "BARRIER_REVIEWED",
  ROUTE_RISK_CHANGED: "ROUTE_RISK_CHANGED",
  ASSISTANCE_ACCEPTED: "ASSISTANCE_ACCEPTED",
  ASSISTANCE_ACCEPT_REJECTED: "ASSISTANCE_ACCEPT_REJECTED"
} as const;
export type FlowEventType = (typeof FLOW_EVENT_TYPES)[keyof typeof FLOW_EVENT_TYPES];
